env:
  browser: true

# extends: standard
extends: plugin:prettier/recommended

globals:
  UIkit: readonly
  $: readonly
  hljs: readonly
  H: readonly
  h: readonly
  T: readonly

ignorePatterns: dist/

parser: babel-eslint
rules:
  prettier/prettier: 0
